version: "3.8"
services:
  backend:
    build: ./backend
    container_name: jokesVille_server
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: jokesVille_client
    ports:
      - "3000:3000"

